### ISSUE TITLE
some problem in scripts directory related to two launch files

### ISSUE THREAD

**Issue by ataeiamirhosein** [nokia/wireless-suite#13]
hello;
I am a master student of telecom in Politecnico di Milano under the supervision of prof. Giacomo Verticale and we work on this platform and edited some section that I described...

## in file ` launch_agent.py ` I change some lines as below:  
add ``` from sacred.observers import MongoObserver ``` after ``` from sacred import Experiment ``` for running like MongoDB observer.  

#  

## in file `launch_q_learn_umts_olpc.py` I changed some lines as below:  
- also, add ``` from sacred.observers import MongoObserver ``` after ``` from sacred import Experiment ``` for running like MongoDB observer.  
- we have a problem with the ` done ` parameter in loop so change;  

```
if done:
    break
```
to
```
if s == num_episodes:
    break
```
in the section of ` # Collect progress ` because ` done ` not execute and we ran into out dimension.  
- in the section of ` # Plot results ` we actually do not need the first ``` plot.figure() ```  

thanks

**Comment by alvarovalcarce** [comment]
Hi,
yes, you can add MongoDB observers if you want.

What is exactly the problem with the ` done` parameter?

**Comment by ataeiamirhosein** [comment]
actually in the file of `launch_q_learn_umts_olpc.py` when running the code
```
if done:
    break
```
__not execute and not break the code. so, I get an error about the dimension control__

**Comment by alvarovalcarce** [comment]
Seems to be related to `max_steps_per_episode` in that script. I've changed that. Can you please pull and try again?

**Comment by ataeiamirhosein** [comment]
sure
i will tell you asap

**Comment by ataeiamirhosein** [comment]
I try again and this time problem was solved
perfect
can you please describe about your changes?

**Comment by alvarovalcarce** [comment]
I just read avoided that t_max is read from the json configuration file by default (see the commit). You can, of course, change this if you need.

**Comment by ataeiamirhosein** [comment]
nice
yes, i got it
i wanna work on some new environment and agent
thanks a lot for your help
